### ISSUE TITLE
Truncate player names when too long

### ISSUE THREAD

**Issue by StefanPuia** [StefanPuia/raid-comp#357]
```css
p {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
}
```
